name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
    - uses: coturiv/setup-ionic@v1.1.0
      with:
        # Version range or exact version of Cordova to use
        cordova-version: 9
        # Version range or exact version of Ionic to use
        ionic-version: 1
        run: ionic run
